#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

final_space = true
version = 3

[palette]
  pink = "#f5c2e7"
  lavender = "#b4befe"
  blue = "#89b4fa"
  peach = "#fab387"
  red = "#f38ba8"
  sapphire = "#209fb5"

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "python"
    style = "plain"
    foreground = "p:pink"
    background = "transparent"
    template = "{{ if .Venv }}({{ .Venv }},{{ end }} \ue73c {{ .Full }}) "

    [blocks.segments.properties]
      display_virtual_env = true
      display_version = false            
      display_mode = "environment"  
      fetch_virtual_env = true     
      virtual_env_regex = "(?P<virtual_env>[^/]+)$" # Extract the env name 

  [[blocks.segments]]
    type = "path"
    style = "plain"
    foreground = "p:pink"
    background = "transparent"
    template = "{{ .Path }}"

    [blocks.segments.properties]
      style = "full"
    
  [[blocks.segments]]
    type = "git"
    style = "plain"
    foreground = "p:lavender"
    background = "transparent"
    template = " {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>"    

    [blocks.segments.properties]
      branch_icon = "\ue725 "
      commit_icon = "\uf417 "
      fetch_status = true

[[blocks]]
  type = "rprompt"
  overflow = "hidden"

  [[blocks.segments]]
    type = "executiontime"
    style = "plain"
    foreground = "p:peach"
    background = "transparent"
    template = "{{ .FormattedMs }}" 

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground_templates = [
      "{{ if gt .Code 0 }}p:red{{end}}",
      "{{ if eq .Code 0 }}p:base{{end}}",
    ]
    background = "transparent"
    template = "❯"

[transient_prompt]
  foreground_templates = [
    "{{ if gt .Code 0 }}p:red{{end}}",
    "{{ if eq .Code 0 }}p:sapphire{{end}}",
  ]
  background = "transparent"
  template = "❯ "

[secondary_prompt]
  foreground = "p:sapphire"
  background = "transparent"
  template = "❯❯ "

