#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

final_space = true
version = 3

[palette]
  # sumiInk0 = "#16161D"
  # sumiInk1 = "#181820"
  # sumiInk2 = "#1a1a22"
  # sumiInk3 = "#1F1F28"
  # sumiInk4 = "#2A2A37"
  # sumiInk5 = "#363646"
  # sumiInk6 = "#54546D"
  # waveBlue1 = "#223249"
  # waveBlue2 = "#2D4F67"
  # winterGreen = "#2B3328"
  # winterYellow = "#49443C"
  # winterRed = "#43242B"
  # winterBlue = "#252535"
  # autumnGreen = "#76946A"
  # autumnRed = "#C34043"
  # autumnYellow = "#DCA561"
  samuraiRed = "#E82424"
  # roninYellow = "#FF9E3B"
  # waveAqua1 = "#6A9589"
  # dragonBlue = "#658594"
  # oldWhite = "#C8C093"
  fujiWhite = "#DCD7BA"
  # fujiGray = "#727169"
  # oniViolet = "#957FB8"
  # oniViolet2 = "#b8b4d0"
  # crystalBlue = "#7E9CD8"
  # springViolet1 = "#938AA9"
  # springViolet2 = "#9CABCA"
  # springBlue = "#7FB4CA"
  waveAqua2 = "#7AA89F" # improve lightness: desaturated greenish Aqua
  springGreen = "#98BB6C"
  # boatYellow1 = "#938056"
  # boatYellow2 = "#C0A36E"
  carpYellow = "#E6C384"
  sakuraPink = "#D27E99"
  # waveRed = "#E46876"
  # peachRed = "#FF5D62"
  surimiOrange = "#FFA066"
  # katanaGray = "#717C7C

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "python"
    style = "plain"
    foreground = "p:fujiWhite"
    background = "transparent"
    template = "{{ if .Venv }}({{ .Venv }},{{ end }} \ue73c {{ .Full }}) "

    [blocks.segments.properties]
      display_virtual_env = true
      display_version = false            
      display_mode = "environment"  
      fetch_virtual_env = true     
      virtual_env_regex = "(?P<virtual_env>[^/]+)$" # Extract the env name 

  [[blocks.segments]]
    type = "path"
    style = "plain"
    foreground = "p:sakuraPink"
    background = "transparent"
    template = "{{ .Path }}"

    [blocks.segments.properties]
      style = "full"
    
  [[blocks.segments]]
    type = "git"
    style = "plain"
    foreground = "p:carpYellow"
    background = "transparent"
    template = " {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>"    

    [blocks.segments.properties]
      branch_icon = "\ue725 "
      commit_icon = "\uf417 "
      fetch_status = true

[[blocks]]
  type = "rprompt"
  overflow = "hidden"

  [[blocks.segments]]
    type = "executiontime"
    style = "plain"
    foreground = "p:surimiOrange"
    background = "transparent"
    template = "{{ .FormattedMs }}" 

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground_templates = [
      "{{ if gt .Code 0 }}p:samuraiRed{{end}}",
      "{{ if eq .Code 0 }}p:base{{end}}",
    ]
    background = "transparent"
    template = "❯"

[transient_prompt]
  foreground_templates = [
    "{{ if gt .Code 0 }}p:samuraiRed{{end}}",
    "{{ if eq .Code 0 }}p:springGreen{{end}}",
  ]
  background = "transparent"
  template = "❯ "

[secondary_prompt]
  foreground = "p:waveAqua2"
  background = "transparent"
  template = "❯❯ "

